### ISSUE TITLE
Java end of life issue

### ISSUE THREAD

**Issue by TheReaperD** [sbbholmes/VisionSkills.xyz#2]
I would recommend not using Java for the application as the browser plugin is being end of lifed on all major browsers and asking the users to install the Java SE environment to make it work would place a burden on users and open them up to the many security risks that have been associated with Java.  If at all possible, I recommend sticking with HTML5+Javascript for the user interface.  Java can still be used server side if it's the best solution as the above issues tend not to affect the server side so much.

**Comment by sbbholmes** [comment]
Thanks for the heads up. The main objective of the project is making vision skill training more accessible, and the stand alone apps are a future concern, mainly for those users who, for various reasons, are not able to enable javascript.
